# Generated by Django 4.2.23 on 2025-12-03 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("garage", "0002_dealership_car_dealership"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="car",
            options={"ordering": ["-year", "make"]},
        ),
    ]
